license: true

image:
  repository: cp.icr.io/cp/cp4a/odm
  pullSecrets:
  - icregistry-secret

internalDatabase:
  persistence:
    enabled: false
  populateSampleData: true

oidc:
  enabled: true

customization:
  authSecretRef: okta-auth-secret
  trustedCertificateList:
  - okta-secret
