customization:
  runAsUser: ''
  securitySecretRef: my-server-secret
  trustedCertificateList:
    - my-client-secret
decisionServerRuntime:
  enableMutualTLS: true
image:
  pullSecrets:
    - registrysecret
  repository: cp.icr.io/cp/cp4a/odm
internalDatabase:
  persistence:
    enabled: false
    useDynamicProvisioning: false
  populateSampleData: true
  runAsUser: ''
license: true
service:
  enableRoute: true
usersPassword: odmAdmin
