customization:
  runAsUser: ''
image:
  pullSecrets:
    - ibm-entitlement-key
  repository: cp.icr.io/cp/cp4a/odm
internalDatabase:
  persistence:
    enabled: false
    useDynamicProvisioning: false
  populateSampleData: true
  runAsUser: ''
license: true
service:
  enableRoute: true
usersPassword: odmAdmin
